import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        headline: ["Syne", "sans-serif"],
        body: ["DM Sans", "sans-serif"],
        label: ["DM Sans", "sans-serif"],
      },
      colors: {
"on-primary-fixed-variant": "#e2e2e2",
                        "on-primary-container": "#000000",
                        "on-background": "#e2e2e2",
                        "error-container": "#93000a",
                        "surface-variant": "#353535",
                        "surface-tint": "#c6c6c7",
                        "on-primary-fixed": "#ffffff",
                        "outline": "#919191",
                        "secondary": "#00dce5",
                        "primary-fixed-dim": "#454747",
                        "on-secondary-fixed": "#002021",
                        "on-tertiary-fixed-variant": "#63f7ff",
                        "error": "#ffb4ab",
                        "surface-container-low": "#1b1b1b",
                        "on-error-container": "#ffdad6",
                        "on-error": "#690005",
                        "surface-container-highest": "#353535",
                        "primary": "#ffffff",
                        "on-secondary-container": "#63f7ff",
                        "tertiary-fixed": "#00696e",
                        "surface-dim": "#131313",
                        "on-surface": "#e2e2e2",
                        "tertiary-fixed-dim": "#004f53",
                        "background": "#131313",
                        "surface-bright": "#393939",
                        "on-secondary": "#002021",
                        "primary-container": "#d4d4d4",
                        "inverse-on-surface": "#303030",
                        "inverse-primary": "#5d5f5f",
                        "surface": "#131313",
                        "tertiary-container": "#00a1a7",
                        "secondary-container": "#004f53",
                        "on-surface-variant": "#c6c6c6",
                        "on-tertiary": "#002021",
                        "surface-container": "#1f1f1f",
                        "on-secondary-fixed-variant": "#004346",
                        "on-tertiary-fixed": "#ffffff",
                        "tertiary": "#63f7ff",
                        "on-tertiary-container": "#000000",
                        "surface-container-high": "#2a2a2a",
                        "outline-variant": "#474747",
                        "primary-fixed": "#5d5f5f",
                        "inverse-surface": "#e2e2e2",
                        "on-primary": "#1a1c1c",
                        "surface-container-lowest": "#0e0e0e",
                        "secondary-fixed": "#00dce5",
                        "secondary-fixed-dim": "#00bec6",
"surface-container-high": "#ffd6f9",
              "surface-dim": "#ffc0fa",
              "secondary": "#834484",
              "on-secondary-fixed": "#561a59",
              "tertiary-container": "#79f788",
              "tertiary": "#006b25",
              "primary-fixed-dim": "#f56364",
              "surface-tint": "#aa2c32",
              "secondary-container": "#ffbcfa",
              "on-tertiary-container": "#005b1f",
              "secondary-dim": "#753777",
              "surface-bright": "#fff3f9",
              "surface-container-low": "#ffebf9",
              "on-secondary-container": "#6c2f6e",
              "inverse-on-surface": "#cc84c9",
              "on-primary": "#ffefee",
              "inverse-surface": "#210024",
              "primary": "#aa2c32",
              "error-container": "#f95630",
              "on-tertiary-fixed-variant": "#006623",
              "secondary-fixed-dim": "#f6aaf2",
              "surface-container-highest": "#ffcef9",
              "on-primary-container": "#4e0009",
              "outline-variant": "#dd94db",
              "on-secondary": "#ffeef9",
              "on-primary-fixed-variant": "#60000d",
              "secondary-fixed": "#ffbcfa",
              "background": "#fff3f9",
              "tertiary-fixed": "#79f788",
              "inverse-primary": "#ff6b6b",
              "primary-fixed": "#ff7574",
              "primary-container": "#ff7574",
              "surface-container": "#ffdff9",
              "surface-container-lowest": "#ffffff",
              "outline": "#a25fa1",
              "primary-dim": "#992027",
              "on-error-container": "#520c00",
              "on-error": "#ffefec",
              "tertiary-fixed-dim": "#6be87b",
              "on-background": "#4f1453",
              "error-dim": "#b92902",
              "on-tertiary": "#d0ffcc",
              "surface-variant": "#ffcef9",
              "on-surface-variant": "#834484",
              "on-secondary-fixed-variant": "#773978",
              "error": "#b02500",
              "on-tertiary-fixed": "#004616",
              "on-primary-fixed": "#000000",
              "tertiary-dim": "#005d1f",
              "on-surface": "#4f1453",
              "surface": "#fff3f9",

        "tertiary-fixed-dim": "#cdbdff",
        "primary-container": "#0a192f",
        "on-surface-variant": "#c5c6cd",
        "on-primary-fixed-variant": "#39475f",
        "surface-container-lowest": "#070d1f",
        "surface-container-low": "#151b2d",
        "surface-container-high": "#23293c",
        "surface-container": "#191f31",
        "inverse-surface": "#dce1fb",
        "surface-tint": "#b9c7e4",
        "surface-variant": "#2e3447",
        "tertiary-container": "#1d0058",
        "inverse-on-surface": "#2a3043",
        "primary-fixed": "#d6e3ff",
        "secondary-fixed": "#5ffbd6",
        "surface-container-highest": "#2e3447",
        "tertiary-fixed": "#e8deff",
        "on-error": "#690005",
        "on-tertiary-container": "#8b66ff",
        "on-secondary-fixed": "#002019",
        "on-tertiary": "#370096",
        "on-primary-fixed": "#0d1c32",
        "surface-bright": "#33394c",
        "on-background": "#dce1fb",
        "error": "#ffb4ab",
        "surface": "#0c1324",
        "inverse-primary": "#515f78",
        "surface-dim": "#0c1324",
        "on-tertiary-fixed-variant": "#4f00d0",
        "outline": "#8f9097",
        "on-secondary-fixed-variant": "#005142",
        "outline-variant": "#44474d",
        "secondary-container": "#00c7a5",
        "primary-fixed-dim": "#b9c7e4",
        "on-secondary": "#00382d",
        "on-primary-container": "#74829d",
        "error-container": "#93000a",
        "on-primary": "#233148",
        "secondary-fixed-dim": "#38debb",
        "on-surface": "#dce1fb",
        "on-tertiary-fixed": "#20005f",
        "tertiary": "#cdbdff",
        "background": "#0c1324",
        "on-secondary-container": "#004d3f",
        "on-error-container": "#ffdad6",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        heading: "hsl(var(--heading))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      backgroundImage: {
        "gradient-primary": "var(--gradient-primary)",
        "gradient-accent": "var(--gradient-accent)",
        "gradient-hero": "var(--gradient-hero)",
        "gradient-card": "var(--gradient-card)",
      },
      boxShadow: {
        smooth: "var(--shadow-smooth)",
        floating: "var(--shadow-floating)",
        glow: "var(--shadow-glow)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [import("tailwindcss-animate")],
} satisfies Config;
